apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: 486066960729.dkr.ecr.eu-central-1.amazonaws.com/auth:latest
        name: auth
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: secret
          - name: JWT_EXPIRES_IN
            value: '3600'
          - name: HTTP_PORT
            value: '3003'
          - name: TCP_PORT
            value: '3002'
        ports:
          - containerPort: 3002
          - containerPort: 3003