version: 0.2

phases:
    pre_build:
        commands:
        - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 486066960729.dkr.ecr.eu-central-1.amazonaws.com
    build:
      commands:
        - docker build -t reservations -f ./apps/reservations/Dockerfile .
        - docker tag reservations:latest 486066960729.dkr.ecr.eu-central-1.amazonaws.com/reservations:latest

        - docker build -t notifications -f ./apps/notifications/Dockerfile .
        - docker tag notifications:latest 486066960729.dkr.ecr.eu-central-1.amazonaws.com/notifications:latest

        - docker build -t auth -f ./apps/auth/Dockerfile .
        - docker tag auth:latest 486066960729.dkr.ecr.eu-central-1.amazonaws.com/auth:latest

        - docker build -t payments -f ./apps/payments/Dockerfile .
        - docker tag payments:latest 486066960729.dkr.ecr.eu-central-1.amazonaws.com/payments:latest

    post_build:
        commands:
          - docker push 486066960729.dkr.ecr.eu-central-1.amazonaws.com/reservations:latest
          - docker push 486066960729.dkr.ecr.eu-central-1.amazonaws.com/notifications:latest
          - docker push 486066960729.dkr.ecr.eu-central-1.amazonaws.com/auth:latest
          - docker push 486066960729.dkr.ecr.eu-central-1.amazonaws.com/payments:latest
          - echo "Completed the build and push of the images to ECR"