version: '3.8'

services:
  reservations:
    build:
        context: .
        dockerfile: ./apps/reservations/Dockerfile
        target: development
    command: pnpm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:debug auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
      - "9230:9229"
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:debug payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
    ports:
      - "9231:9229"
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:debug notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
    ports:
      - "9232:9229"
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Set root username
      MONGO_INITDB_ROOT_PASSWORD: example  # Set root password
    volumes:
      - mongo_data:/data/db  # Persist data
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  mongo_data:

networks:
    backend:
        driver: bridge