apiVersion: v1
data:
  clientSecret: R09DU1BYLXRCelZtVEdXcE9PenNSN2NVQ3hDS1pWa1NpeFk=
  refreshToken: MS8vMDRwSUhwYU05aFhta0NnWUlBUkFBR0FRU053Ri1MOUlyNUF6ejBnYnM4SWhuaEZPdWt2b3U3SXZPY0F6dy1McGxILUhlVjRqVlZfTS0yejRIU0VZSGJoWFNjYjJ5elZJUWtvSQ==
kind: Secret
metadata:
  creationTimestamp: "2024-11-11T11:46:32Z"
  name: google
  namespace: default
  resourceVersion: "464107"
  uid: 5778fae3-7d91-4b25-9186-d92360a538a8
type: Opaque
