apiVersion: v1
data:
  secret: NFlkT2ZpUHR5djFhWUFqU2RyN01pZFBPbm1aSHRUNEFkTEF2UWxkcEh2RDJTUk93RVhTN0UxSlFIaFVuMFhFeTBiT0NDSG5JOHpJeFdLb2NJN0FTYjdLaDN1UTBzcG45RnNa
kind: Secret
metadata:
  creationTimestamp: "2024-11-11T12:34:08Z"
  name: jwt
  namespace: default
  resourceVersion: "471330"
  uid: 51d89a50-6862-4644-8300-10ed6befad45
type: Opaque
